#include "textdraw_base_wrapper.hpp"
#include "../../converter/types.hpp"
#include "../../converter/entity.hpp"
#include "../../converter/vehicle.hpp"
#include "../gtaquat/gtaquat_wrapper.hpp"

WRAP_BASIC_WITH_CONSTRUCTOR_INHERIT(ITextDrawBase, IIDProvider)

WRAP_BASIC_CALL_RETURN(ITextDrawBase, getPosition, (Vector2, VectorToJS<Vector2>))
WRAP_BASIC_CALL_RETURN(ITextDrawBase, setPosition, (ITextDrawBase&, EntityToJS<ITextDrawBase>), (Vector2, JSToVector<Vector2>, position))
WRAP_BASIC_CALL(ITextDrawBase, setText, (Impl::String, FROM_JS_FN(String), text))
WRAP_BASIC_CALL_RETURN(ITextDrawBase, getText, (StringView, TO_JS_FN(StringView)))
WRAP_BASIC_CALL_RETURN(ITextDrawBase, setLetterSize, (ITextDrawBase&, EntityToJS<ITextDrawBase>), (Vector2, JSToVector<Vector2>, size))
WRAP_BASIC_CALL_RETURN(ITextDrawBase, getLetterSize, (Vector2, VectorToJS<Vector2>))
WRAP_BASIC_CALL_RETURN(ITextDrawBase, setTextSize, (ITextDrawBase&, EntityToJS<ITextDrawBase>), (Vector2, JSToVector<Vector2>, size))
WRAP_BASIC_CALL_RETURN(ITextDrawBase, getTextSize, (Vector2, VectorToJS<Vector2>))
WRAP_BASIC_CALL_RETURN(ITextDrawBase, setAlignment, (ITextDrawBase&, EntityToJS<ITextDrawBase>), (TextDrawAlignmentTypes, JSToEnum<TextDrawAlignmentTypes>, alignment))
WRAP_BASIC_CALL_RETURN(ITextDrawBase, getAlignment, (TextDrawAlignmentTypes, EnumToJS<TextDrawAlignmentTypes>))
WRAP_BASIC_CALL_RETURN(ITextDrawBase, setColour, (ITextDrawBase&, EntityToJS<ITextDrawBase>), (Colour, FROM_JS_FN(Colour), colour))
WRAP_BASIC_CALL_RETURN(ITextDrawBase, getLetterColour, (Colour, TO_JS_FN(Colour)))
WRAP_BASIC_CALL_RETURN(ITextDrawBase, useBox, (ITextDrawBase&, EntityToJS<ITextDrawBase>), (bool, JSToBool, use))
WRAP_BASIC_CALL_RETURN(ITextDrawBase, hasBox, (bool, BoolToJS))
WRAP_BASIC_CALL_RETURN(ITextDrawBase, setBoxColour, (ITextDrawBase&, EntityToJS<ITextDrawBase>), (Colour, FROM_JS_FN(Colour), colour))
WRAP_BASIC_CALL_RETURN(ITextDrawBase, getBoxColour, (Colour, TO_JS_FN(Colour)))
WRAP_BASIC_CALL_RETURN(ITextDrawBase, setShadow, (ITextDrawBase&, EntityToJS<ITextDrawBase>), (int, JSToInt<int>, shadow))
WRAP_BASIC_CALL_RETURN(ITextDrawBase, getShadow, (int, IntToJS<int>))
WRAP_BASIC_CALL_RETURN(ITextDrawBase, setOutline, (ITextDrawBase&, EntityToJS<ITextDrawBase>), (int, JSToInt<int>, outline))
WRAP_BASIC_CALL_RETURN(ITextDrawBase, getOutline, (int, IntToJS<int>))
WRAP_BASIC_CALL_RETURN(ITextDrawBase, setBackgroundColour, (ITextDrawBase&, EntityToJS<ITextDrawBase>), (Colour, FROM_JS_FN(Colour), colour))
WRAP_BASIC_CALL_RETURN(ITextDrawBase, getBackgroundColour, (Colour, TO_JS_FN(Colour)))
WRAP_BASIC_CALL_RETURN(ITextDrawBase, setStyle, (ITextDrawBase&, EntityToJS<ITextDrawBase>), (TextDrawStyle, JSToEnum<TextDrawStyle>, style))
WRAP_BASIC_CALL_RETURN(ITextDrawBase, getStyle, (TextDrawStyle, EnumToJS<TextDrawStyle>))
WRAP_BASIC_CALL_RETURN(ITextDrawBase, setProportional, (ITextDrawBase&, EntityToJS<ITextDrawBase>), (bool, JSToBool, proportional))
WRAP_BASIC_CALL_RETURN(ITextDrawBase, isProportional, (bool, BoolToJS))
WRAP_BASIC_CALL_RETURN(ITextDrawBase, setSelectable, (ITextDrawBase&, EntityToJS<ITextDrawBase>), (bool, JSToBool, selectable))
WRAP_BASIC_CALL_RETURN(ITextDrawBase, isSelectable, (bool, BoolToJS))
WRAP_BASIC_CALL_RETURN(ITextDrawBase, setPreviewModel, (ITextDrawBase&, EntityToJS<ITextDrawBase>), (int, JSToInt<int>, model))
WRAP_BASIC_CALL_RETURN(ITextDrawBase, getPreviewModel, (int, IntToJS<int>))
WRAP_BASIC_CALL_RETURN(ITextDrawBase, setPreviewRotation, (ITextDrawBase&, EntityToJS<ITextDrawBase>), (GTAQuat, FROM_JS_FN(GTAQuat), rotation))
WRAP_BASIC_CALL_RETURN(ITextDrawBase, getPreviewRotation, (GTAQuat, TO_JS_FN(GTAQuat)))
WRAP_BASIC_CALL_RETURN(ITextDrawBase, setPreviewVehicleColour, (ITextDrawBase&, EntityToJS<ITextDrawBase>), (int, JSToInt<int>, colour1), (int, JSToInt<int>, colour2))
WRAP_BASIC_CALL_RETURN(ITextDrawBase, getPreviewVehicleColour, (VehicleColour, TO_JS_FN(VehicleColour)))
WRAP_BASIC_CALL_RETURN(ITextDrawBase, setPreviewZoom, (ITextDrawBase&, EntityToJS<ITextDrawBase>), (float, JSToFloat, zoom))
WRAP_BASIC_CALL_RETURN(ITextDrawBase, getPreviewZoom, (float, FloatToJS))
WRAP_BASIC_CALL(ITextDrawBase, restream)
