#include "v8.h"

v8::Local<v8::Value> WrapPlayerWeapon(v8::Local<v8::Context> context) {
    auto settableCoreDataTypeHandle =
        EnumToObject<PlayerWeapon>({{"PlayerWeapon_Fist",              PlayerWeapon::PlayerWeapon_Fist},
                                    {"PlayerWeapon_BrassKnuckle",      PlayerWeapon::PlayerWeapon_BrassKnuckle},
                                    {"PlayerWeapon_GolfClub",          PlayerWeapon::PlayerWeapon_GolfClub},
                                    {"PlayerWeapon_NiteStick",         PlayerWeapon::PlayerWeapon_NiteStick},
                                    {"PlayerWeapon_Knife",             PlayerWeapon::PlayerWeapon_Knife},
                                    {"PlayerWeapon_Bat",               PlayerWeapon::PlayerWeapon_Bat},
                                    {"PlayerWeapon_Shovel",            PlayerWeapon::PlayerWeapon_Shovel},
                                    {"PlayerWeapon_PoolStick",         PlayerWeapon::PlayerWeapon_PoolStick},
                                    {"PlayerWeapon_Katana",            PlayerWeapon::PlayerWeapon_Katana},
                                    {"PlayerWeapon_Chainsaw",          PlayerWeapon::PlayerWeapon_Chainsaw},
                                    {"PlayerWeapon_Dildo",             PlayerWeapon::PlayerWeapon_Dildo},
                                    {"PlayerWeapon_Dildo2",            PlayerWeapon::PlayerWeapon_Dildo2},
                                    {"PlayerWeapon_Vibrator",          PlayerWeapon::PlayerWeapon_Vibrator},
                                    {"PlayerWeapon_Vibrator2",         PlayerWeapon::PlayerWeapon_Vibrator2},
                                    {"PlayerWeapon_Flower",            PlayerWeapon::PlayerWeapon_Flower},
                                    {"PlayerWeapon_Cane",              PlayerWeapon::PlayerWeapon_Cane},
                                    {"PlayerWeapon_Grenade",           PlayerWeapon::PlayerWeapon_Grenade},
                                    {"PlayerWeapon_Teargas",           PlayerWeapon::PlayerWeapon_Teargas},
                                    {"PlayerWeapon_Moltov",            PlayerWeapon::PlayerWeapon_Moltov},
                                    {"PlayerWeapon_Colt45",            PlayerWeapon::PlayerWeapon_Colt45},
                                    {"PlayerWeapon_Silenced",          PlayerWeapon::PlayerWeapon_Silenced},
                                    {"PlayerWeapon_Deagle",            PlayerWeapon::PlayerWeapon_Deagle},
                                    {"PlayerWeapon_Shotgun",           PlayerWeapon::PlayerWeapon_Shotgun},
                                    {"PlayerWeapon_Sawedoff",          PlayerWeapon::PlayerWeapon_Sawedoff},
                                    {"PlayerWeapon_Shotgspa",          PlayerWeapon::PlayerWeapon_Shotgspa},
                                    {"PlayerWeapon_UZI",               PlayerWeapon::PlayerWeapon_UZI},
                                    {"PlayerWeapon_MP5",               PlayerWeapon::PlayerWeapon_MP5},
                                    {"PlayerWeapon_AK47",              PlayerWeapon::PlayerWeapon_AK47},
                                    {"PlayerWeapon_M4",                PlayerWeapon::PlayerWeapon_M4},
                                    {"PlayerWeapon_TEC9",              PlayerWeapon::PlayerWeapon_TEC9},
                                    {"PlayerWeapon_Rifle",             PlayerWeapon::PlayerWeapon_Rifle},
                                    {"PlayerWeapon_Sniper",            PlayerWeapon::PlayerWeapon_Sniper},
                                    {"PlayerWeapon_RocketLauncher",    PlayerWeapon::PlayerWeapon_RocketLauncher},
                                    {"PlayerWeapon_HeatSeeker",        PlayerWeapon::PlayerWeapon_HeatSeeker},
                                    {"PlayerWeapon_FlameThrower",      PlayerWeapon::PlayerWeapon_FlameThrower},
                                    {"PlayerWeapon_Minigun",           PlayerWeapon::PlayerWeapon_Minigun},
                                    {"PlayerWeapon_Satchel",           PlayerWeapon::PlayerWeapon_Satchel},
                                    {"PlayerWeapon_Bomb",              PlayerWeapon::PlayerWeapon_Bomb},
                                    {"PlayerWeapon_SprayCan",          PlayerWeapon::PlayerWeapon_SprayCan},
                                    {"PlayerWeapon_FireExtinguisher",  PlayerWeapon::PlayerWeapon_FireExtinguisher},
                                    {"PlayerWeapon_Camera",            PlayerWeapon::PlayerWeapon_Camera},
                                    {"PlayerWeapon_Night_Vis_Goggles", PlayerWeapon::PlayerWeapon_Night_Vis_Goggles},
                                    {"PlayerWeapon_Thermal_Goggles",   PlayerWeapon::PlayerWeapon_Thermal_Goggles},
                                    {"PlayerWeapon_Parachute",         PlayerWeapon::PlayerWeapon_Parachute},
                                    {"PlayerWeapon_Vehicle",           PlayerWeapon::PlayerWeapon_Vehicle},
                                    {"PlayerWeapon_Heliblades",        PlayerWeapon::PlayerWeapon_Heliblades},
                                    {"PlayerWeapon_Explosion",         PlayerWeapon::PlayerWeapon_Explosion},
                                    {"PlayerWeapon_Drown",             PlayerWeapon::PlayerWeapon_Drown},
                                    {"PlayerWeapon_Collision",         PlayerWeapon::PlayerWeapon_Collision},
                                    {"PlayerWeapon_End",               PlayerWeapon::PlayerWeapon_End}}, context);

    return settableCoreDataTypeHandle;
}